### ISSUE TITLE
Template Color Scale

### ISSUE THREAD

**Issue by kristenvincent** [uwcart/mapstudy#12]
Color scale dropdown under resymbolize control doesn't show options

**Comment by northlandiguana** [comment]
This seems to be a problem in Chrome and possibly Safari (I don't have a Mac so haven't been able to check yet). I added a separate color scale preview palette next to the dropdown menu as a temporary fix, but will ultimately have to build a custom dropdown UI to address the issue.

**Comment by northlandiguana** [comment]
Replaced select element with custom dropdown UI that displays all color scales across browsers.
