### ISSUE TITLE
Every dataLayer becomes an overlay

### ISSUE THREAD

**Issue by kristenvincent** [uwcart/mapstudy#35]
When overlay is implemented, every dataLayer becomes an overlay even when just a few layers are named in the dataLayers array for the overlay interaction properties. For example, Company isn't the only layer that becomes an overlay. They all do. 

"overlay": {
		"logging": true,
		"toggle": false,
		"dataLayers": [
		"Company"
			]

**Comment by northlandiguana** [comment]
Added test for layer in overlay.dataLayers.
